caiso_curtailment_reports:
  first_available_date: 2021-06-18
  url:
    standard: 'https://www.caiso.com/Documents/Curtailed-non-operational-generator-prior-trade-date-report-%Y%m%d.xlsx'
    exceptions:
      - type: list
        dates: [2024-05-31]
        template: 'https://www.caiso.com/Documents/Curtailed-non-operational-generator-prior-trade-date-report-%Y-%m-%d.xlsx'
      - type: list
        dates: [2024-06-01]
        template: 'https://www.caiso.com/Documents/Curtailed-and-non-operational-generator-prior-trade-date-report-%b-%d-%Y.xlsx'
      - type: range
        dates: [2024-06-02,2025-01-12]
        template:  'https://www.caiso.com/Documents/Curtailed-non-operational-generator-prior-trade-date-report-%b-%d-%Y.xlsx'
  download_path_template: 'downloads\caiso_curtailment_reports\PriorTradeDateCurtailments_%Y-%m-%d.xlsx'
  combined_reports_path: 'downloads\caiso_curtailment_reports.parquet'
  download_log_path: 'logs\curtailments_download_log.csv'
  text_log_path: 'logs\curtailments_download_log.txt'
caiso_master_capability_list:
  download_path: 'config\master_capability_list.parquet'
caiso_master_file:
  download_path: 'config\master_file.parquet'
demand_hours_analysis:
  resource_demand_hours_path: 'results\resource_demand_hours.parquet'
ucap_analysis:
  text_log_path: 'logs\ucap_analysis_log.txt'
  natures_of_work:
    # Identified in 2024:
    # - PLANT_TROUBLE
    # - METERING_TELEMETRY
    # - TRANSMISSION_INDUCED
    # - TECHNICAL_LIMITATIONS_NOT_IN_MARKET_MODEL
    # - TRANSITIONAL_LIMITATION
    # - ENVIRONMENTAL_RESTRICTIONS
    # - ICCP
    # - RTU_RIG

    # Included in CAISO's 2025 analysis:
    # - AMBIENT_DUE_TO_TEMP
    # - AVR_EXITER
    # - ENVIRONMENTAL_RESTRICTIONS
    # - ICCP
    # - METERING_TELEMETRY
    # - PLANT_MAINTENANCE
    # - PLANT_TROUBLE
    # - POWER_SYSTEM_STABILIZATION
    # - RTU_RIG
    # - TECHNICAL_LIMITATIONS_NOT_IN_MARKET_MODEL
    # - TRANSITIONAL_LIMITATION

    # Include most codes:
    - AMBIENT_DUE_TO_FUEL_INSUFFICIENCY
    - AMBIENT_DUE_TO_TEMP
    - AMBIENT_NOT_DUE_TO_TEMP
    - ANNUAL_USE_LIMIT_REACHED
    - AVR_EXITER
    - ENVIRONMENTAL_RESTRICTIONS
    - ICCP
    - METERING_TELEMETRY
    - MONTHLY_USE_LIMIT_REACHED
    - NEW_GENERATOR_TEST_ENERGY
    - OTHER_USE_LIMIT_REACHED
    - PLANT_MAINTENANCE
    - PLANT_TROUBLE
    - POWER_SYSTEM_STABILIZATION
    - RIMS_OUTAGE
    - RIMS_TESTING
    - RTU_RIG
    - SHORT_TERM_USE_LIMIT_REACHED
    - TECHNICAL_LIMITATIONS_NOT_IN_MARKET_MODEL
    - TRANSITIONAL_LIMITATION
    - TRANSMISSION_INDUCED
    - UNIT_SUPPORTING_STARTUP
    - UNIT_TESTING
  years: [2022,2023,2024]
  seasons:
    summer: [[Jun 1, Oct 31]]
    nonsummer: [[Jan 1, May 30], [Nov 1, Dec 31]]
  hour_filter_path: 'config\availability_assessment_hours_2022-2024.csv'
  results:
    outage_path_template: 'results\eford_by_resource_and_NOW_AAH_[years].csv'
    demand_hours_path_template: 'results\demand_hours_by_resource_AAH_[years].csv'
