caiso_curtailment_reports:
  first_available_date: 2021-06-18
  url:
    standard: 'https://www.caiso.com/Documents/Curtailed-non-operational-generator-prior-trade-date-report-%Y%m%d.xlsx'
    exceptions:
      - type: list
        dates: [2024-05-31]
        template: 'https://www.caiso.com/Documents/Curtailed-non-operational-generator-prior-trade-date-report-%Y-%m-%d.xlsx'
      - type: list
        dates: [2024-06-01]
        template: 'https://www.caiso.com/Documents/Curtailed-and-non-operational-generator-prior-trade-date-report-%b-%d-%Y.xlsx'
      - type: range
        dates: [2024-06-02,2025-01-12]
        template:  'https://www.caiso.com/Documents/Curtailed-non-operational-generator-prior-trade-date-report-%b-%d-%Y.xlsx'
  download_path_template: 'downloads\caiso_curtailment_reports\PriorTradeDateCurtailments_%Y-%m-%d.xlsx'
  combined_reports_path: 'downloads\caiso_curtailment_reports.parquet'
  download_log_path: 'logs\curtailments_download_log.csv'
  text_log_path: 'logs\curtailments_download_log.txt'
weather_data:
  urls:
    weather_station_information: 'https://www.ncei.noaa.gov/pub/data/noaa/isd-history.txt'
    normalized_weather_inventory: 'https://www.ncei.noaa.gov/data/normals-hourly/1991-2020/doc/hly_inventory_30yr.txt'
    historic_data_template: 'https://www.ncei.noaa.gov/data/global-hourly/access/[year]/[file_id].csv'
    normalized_weather_year_template: 'https://www.ncei.noaa.gov/data/normals-hourly/1991-2020/access/[country]W[wban].csv'
  download_path_templates:
    historic_data: 'downloads\weather_data\[usaf]-[wban]\[usaf]-[wban]_[year].csv'
    normalized_weather_year: 'downloads\weather_data\[usaf]-[wban]\[usaf]-[wban]_normalized.csv'
  combined_reports_path_template: 'downloads\weather_data_[type].parquet'
  zone_shape_file: 'config\BuildingClimateZonesMap.kmz'
  download_log_path: 'logs\weather_data_download_log.csv'
  text_log_path: 'logs\weather_data_download_log.txt'
resource_information:
  eia_form_860:
    url:
      template: 'https://www.eia.gov/electricity/data/eia860m/xls/[month]_generator[year].xlsx'
    worksheet_names:
      - Operating
      - Planned
      - Retired
  caiso_eia_map:
    path: 'config\caiso_eia_map_2025-12-17.csv'
  master_resource_database:
    path: 'config\MRD Final 2026_09182025 ver2.xlsx'
    worksheet_name: MRD
    caiso_master_capability_list_worksheet_name: 'mastergen (updated SEP)'
demand_hours_analysis:
  resource_demand_hours_path: 'results\resource_demand_hours.parquet'
ucap_analysis:
  text_log_path: 'logs\ucap_analysis_log.txt'
  natures_of_work:
    - AMBIENT_DUE_TO_FUEL_INSUFFICIENCY
    - AMBIENT_DUE_TO_TEMP
    - AMBIENT_NOT_DUE_TO_TEMP
    - ANNUAL_USE_LIMIT_REACHED
    - AVR_EXITER
    - ENVIRONMENTAL_RESTRICTIONS
    - ICCP
    - METERING_TELEMETRY
    - MONTHLY_USE_LIMIT_REACHED
    - NEW_GENERATOR_TEST_ENERGY
    - OTHER_USE_LIMIT_REACHED
    - PLANT_MAINTENANCE
    - PLANT_TROUBLE
    - POWER_SYSTEM_STABILIZATION
    - RIMS_OUTAGE
    - RIMS_TESTING
    - RTU_RIG
    - SHORT_TERM_USE_LIMIT_REACHED
    - TECHNICAL_LIMITATIONS_NOT_IN_MARKET_MODEL
    - TRANSITIONAL_LIMITATION
    - TRANSMISSION_INDUCED
    - UNIT_SUPPORTING_STARTUP
    - UNIT_TESTING
  thermal_resource_types:
    - Biogas
    - Biomass/Wood
    - CCGT
    - CHP
    - Geothermal
    - Peaker
    - Reciprocating Engine
  years: [2022,2023,2024]
  seasons:
    summer: [[Jun 1, Oct 31]]
    nonsummer: [[Jan 1, May 31], [Nov 1, Dec 31]]
  hour_filter_path: 'config\availability_assessment_hours_2022-2024.csv'
  # hour_filter_path: 'config\all_hours_2022-2024.csv'
  results:
    outage_path_template: 'results\eford_by_resource_and_NOW_AAH_[years].csv'
    # outage_path_template: 'results\efor_by_resource_and_NOW_AAH_[years].csv'
    demand_hours_path_template: 'results\demand_hours_by_resource_AAH_[years].csv'
    ambient_derations_due_to_temperature:
      resource_weather_station_pairs_path: 'results\ambient_due_to_temperature\resource_weather_station_pairs.csv'
      deration_curve_parameters_path_template: 'results\ambient_due_to_temperature\deration_curve_parameters_[years].csv'
      normalized_derations_path_template: 'results\ambient_due_to_temperature\normalized_derations_by_resource_[years].parquet'
      normalized_eford_path_template: 'results\ambient_due_to_temperature\normalized_ambient_temperature_eford_by_resource_[years].csv'
